### ISSUE TITLE
Quasar 0.6.2 and Dropwizard 0.8 needs extra config

### ISSUE THREAD

**Issue by afrische** [puniverse/quasar#92]
I noticed some errors after upgrading dropwizard from 0.7.1 to 0.8.1. e.g.
```java
Exception in thread "main" java.lang.NoSuchMethodError: com.codahale.metrics.JmxAttributeGauge.<init>(Ljavax/management/MBeanServerConnection;Ljavax/management/ObjectName;Ljava/lang/String;)V
        at com.codahale.metrics.jvm.BufferPoolMetricSet.getMetrics(BufferPoolMetricSet.java:45)
        at com.codahale.metrics.MetricRegistry.registerAll(MetricRegistry.java:381)
```

The problem is, that the newer dropwizard depends on metrics in a different package group than quasar. 

A workaround is to exclude the com.codahale.metrics group . e.g. in gradle
```groovy
   configurations {
       provided
       capsule
       quasar
       all*.exclude group: 'org.apache.logging.log4j'
       all*.exclude group: 'com.codahale.metrics'
   }
```

**Comment by circlespainter** [comment]
Ca you try with Quasar 0.7.0? It is using Metrics from the `io.dropwizard` package since https://github.com/puniverse/quasar/commit/7a16253030dd079700d1b8e3c0ef2698ad5d4f44

**Comment by afrische** [comment]
In 0.7 it works as expected.
I literary saw the 0.7 release three minutes after completing that writeup. However, since I spend time figuring out how to use q0.6.2 with dw0.8.1, I wanted to publish that info somewhere.

**Comment by circlespainter** [comment]
It can be useful info indeed, maybe you could post it in the user group as well https://groups.google.com/forum/#!forum/quasar-pulsar-user.
