### ISSUE TITLE
NoClassDefFoundError jsr166e after upgrading to 0.7.0

### ISSUE THREAD

**Issue by paulosuzart** [puniverse/quasar#91]
Hello, 

after upgrading I get this error. The java version is:
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

The project I'm trying to run is this: https://github.com/paulosuzart/krust-pm/tree/quasar7, and it works perfectly with 0.6.2. Does Quasar need any specific jre build?

    Exception in thread "main" java.lang.NoClassDefFoundError: jsr166e/ConcurrentHashMapV8
	at co.paralleluniverse.concurrent.util.MapUtil.newConcurrentHashMap(MapUtil.java:20)
	at co.paralleluniverse.fibers.instrument.JavaAgent.<clinit>(JavaAgent.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
    Caused by: java.lang.ClassNotFoundException: jsr166e.ConcurrentHashMapV8
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    FATAL ERROR in native method: processing of -javaagent failed
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

**Comment by circlespainter** [comment]
Yes unfortunately there seems to be an issue with the published JDK8-optimised Quasar 0.7.0. It will be fixed soon, in the meantime please use the non-JDK8 one.

**Comment by circlespainter** [comment]
It is fixed in current master, (soon-to-come) publishing for next release will be fine.
